name: Build Mermaid PNG

on:
  push:
    paths:
      - 'docs/images/**/*.mmd'
      - 'docs/images/*.mmd'
      - '.github/workflows/mermaid-build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docker 版 mermaid-cli を使うので Node や Puppeteer の準備は不要
      - name: Render Mermaid (*.mmd) to PNG via Docker
        run: |
          set -euo pipefail
          shopt -s nullglob
          mkdir -p docs/images
          files=(docs/images/**/*.mmd docs/images/*.mmd)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No .mmd files found under docs/images/"
            exit 0
          fi

          for f in "${files[@]}"; do
            out="${f%.mmd}.png"
            echo "Rendering $f -> $out"
            docker run --rm \
              -v "${GITHUB_WORKSPACE}:/data" \
              ghcr.io/mermaid-js/mermaid-cli:10.9.1 \
              -i "/data/$f" \
              -o "/data/$out" \
              -b transparent \
              -w 1200
          done

      - name: Optimize PNGs (optional)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pngquant
          find docs/images -name '*.png' -print0 | xargs -0 -I{} pngquant --skip-if-larger --force --ext .png {}

      - name: Commit PNGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: render Mermaid PNGs"
          file_pattern: docs/images/*.png
