name: Build Mermaid PNG

on:
  push:
    paths:
      - 'docs/images/*.mmd'
      - '.github/workflows/mermaid-build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install mermaid-cli
        run: |
          npm i -g @mermaid-js/mermaid-cli@10

      - name: Render Mermaid to PNG
        run: |
          mkdir -p docs/images
          for f in docs/images/*.mmd; do
            out="${f%.mmd}.png"
            echo "Rendering $f -> $out"
            mmdc -i "$f" -o "$out" -b transparent -w 1200 -H 0
          done

      - name: Commit PNGs
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/images/*.png
            git commit -m "chore(diagram): render Mermaid PNGs"
            git push
          fi
